feat: added platform-browser, Storage API
Effect-TS/platform pull request #111
Opened 2023-08-26 22:54 UTC by jessekelly881

Just playing around with this following our discussion. Let me know if this looks like something that we are interested in adding and if so what needs to be changed. :)

2023-08-27 01:46 UTC, tim-smart requested changes
Good start! I think we should add a memory and file system variant eventually.

2023-08-27 01:46 UTC, tim-smart commented on packages/platform-browser/docgen.json
> +      "@effect/platform-node": ["./src/index.ts"],
Can remove node here

2023-08-27 01:46 UTC, tim-smart commented on packages/platform-browser/docgen.json
> +      "@effect/platform-node": ["./src/index.ts"],
^^

2023-08-27 01:46 UTC, tim-smart commented on packages/platform-browser/package.json
> +    "busboy": "^1.6.0"
Won't need this dependency. Could probably remove some peer deps too.

2023-08-27 01:46 UTC, tim-smart commented on packages/platform-browser/src/Storage.ts
> +import * as O from "@effect/data/Option"
We prefer using the full name of the modules in effect library code.

Same for "PlatformError"

2023-08-27 01:46 UTC, tim-smart commented on packages/platform-browser/vitest.config.ts
> +      "@effect/platform-node/test": path.join(__dirname, "test"),
Can remove this

2023-08-27 01:46 UTC, tim-smart commented on packages/platform/src/Storage.ts
> +export interface Storage {
I'm thinking `KeyValueStore` is a better name. `Storage` is too generic :)

2023-08-27 01:46 UTC, tim-smart commented on packages/platform/src/Storage.ts
> +  readonly getItem: (key: string) => Effect.Effect<never, PlatformError, O.Option<string>>
I think we just call these get / set / remove.

2023-08-27 01:46 UTC, tim-smart commented on packages/platform/src/Storage.ts
> +  readonly clear: () => Effect.Effect<never, PlatformError, void>
This can be constant.

2023-08-27 01:46 UTC, tim-smart commented on packages/platform/src/Storage.ts
> +  readonly key: (index: number) => Effect.Effect<never, PlatformError, O.Option<string>>
What is the use case for `key`? Just wondering if this will cause issues if we choose to implement a FileSystem variant of the store.

2023-08-27 01:46 UTC, tim-smart commented on packages/platform/src/Storage.ts
> +  readonly length: () => Effect.Effect<never, PlatformError, number>
`size` will be more consistent with other Effect modules.

2023-08-27 01:46 UTC, tim-smart commented on packages/platform/src/Storage.ts
> +export const Storage = Tag<Storage, Storage>()
If you add a TypeId to the store interface, then you can use it for the Tag identifier.

2023-08-27 02:05 UTC, jessekelly881 commented on packages/platform/src/Storage.ts
> +export interface Storage {
The name comes from [here](https://developer.mozilla.org/en-US/docs/Web/API/Storage) but we can definitely change it.

2023-08-27 02:17 UTC, jessekelly881 commented
Thanks! 🙏 I was thinking the same thing. I will add those as well. As far as naming, I think it makes the most sense to stick to the Storage API sense that's already a well defined js interface.

2023-08-27 03:57 UTC, jessekelly881 commented on packages/platform/src/Storage.ts
> +  readonly key: (index: number) => Effect.Effect<never, PlatformError, O.Option<string>>
It might yeah, it's a bit of an awkward api.. I wonder if a fn `keys` that returns a list of all keys makes more sense? In the case of localStorage it can just loop over localhost.key(i) until it returns null...

2023-08-27 21:18 UTC, tim-smart commented
I'm just going to quickly hijack this PR to do a restructure and add the /platform re-exports. Will then review your latest changes :)

2023-08-27 21:41 UTC, jessekelly881 commented
Ok! Go for it!

2023-08-27 21:51 UTC, tim-smart commented on packages/platform/src/Storage.ts
> +  readonly key: (index: number) => Effect.Effect<never, PlatformError, O.Option<string>>
We can leave it out for now.

2023-08-27 22:16 UTC, tim-smart requested changes

2023-08-27 22:16 UTC, tim-smart commented on packages/platform/src/KeyValueStore.ts
> +  ) => Effect.Effect<never, PlatformError.PlatformError, void>
I think this should return a boolean indicating success / failure. This is more consistent with other .modify apis in the ecosystem.

2023-08-27 22:16 UTC, tim-smart commented on packages/platform/src/KeyValueStore.ts
> +  readonly setMany: (values: Record<string, string>) => Effect.Effect<never, PlatformError.PlatformError, void>
I think we should not include set/get/removeMany for now. We can relook at adding them later.

2023-08-27 22:16 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +    clear: Effect.succeed(store.clear()),
This should be Effect.sync. Same for all the other apis.

2023-08-27 22:16 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +        get: (key: string) => fs.readFileString(keyPath(key)).pipe(Effect.map(Option.some)),
Will need to catch the not found errors and map to Option.none

2023-08-27 22:16 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +        clear: fs.remove(directory),
This will lead to errors when trying to create items after clearing. Will need to recreate the folder - should also try to create the directory on construction.

2023-08-27 22:16 UTC, tim-smart commented on packages/platform-browser/src/internal/keyValueStore.ts
> +          method: "length",
"size", the other errors need updating too.

2023-08-27 22:16 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +// createFileSystemTempLayer() -- using the temp file api
Did you want to attempt this?

2023-08-27 22:17 UTC, tim-smart commented
Have moved things around a little and added some feedback :)

2023-08-27 22:19 UTC, jessekelly881 commented on packages/platform/src/KeyValueStore.ts
> +  ) => Effect.Effect<never, PlatformError.PlatformError, void>
I was considering updating this to return the resulting value. Do you think a boolean would be better?

2023-08-27 22:19 UTC, jessekelly881 commented on packages/platform/src/internal/keyValueStore.ts
> +    clear: Effect.succeed(store.clear()),
Ooh good point.

2023-08-27 22:20 UTC, jessekelly881 commented on packages/platform/src/internal/keyValueStore.ts
> +// createFileSystemTempLayer() -- using the temp file api
Yeah, I can do this.

2023-08-27 22:21 UTC, jessekelly881 commented
Ok! I will update it. :)

2023-08-27 22:26 UTC, tim-smart commented on packages/platform/src/KeyValueStore.ts
> +  ) => Effect.Effect<never, PlatformError.PlatformError, void>
Yeah, and don't raise an error if the key is missing. Option<string> is ok too

2023-08-27 22:43 UTC, jessekelly881 commented
Ok! I will update it. :) Btw, do you think we should use a semaphore for localhost.setItem(etc.)?

2023-08-27 23:20 UTC, tim-smart commented
> Ok! I will update it. :) Btw, do you think we should use a semaphore for localhost.setItem(etc.)?

For localStorage/session/memory we don't need one. Should probably add one to the FileSystem implemenations.

2023-08-28 02:10 UTC, jessekelly881 commented
Yeah? Don't readFile and writeFile already have locks though?

2023-08-28 02:36 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +// createFileSystemTempLayer() -- using the temp file api
Ah yep, doesn't make sense, scrap it.

2023-08-28 03:38 UTC, tim-smart commented
> Yeah? Don't readFile and writeFile already have locks though? Do you think we need something on top of that?

No, node doesn't lock files that I'm aware of. But maybe the extra complexity isn't worth it (you would need a lock per key)

2023-08-28 07:02 UTC, jessekelly881 commented on packages/platform/src/KeyValueStore.ts
> +  ) => Effect.Effect<never, PlatformError.PlatformError, void>
I don't think Option<string> makes sense here. The idea is to mutate a key in place(i.e. get value, map value, set value) and having it return the new value would just be a convenience(assuming doing so is a good idea). So I think it should be Effect.Effect<never, PlatformError.PlatformError, string>. If you can't get/set the value then that should be an error.

2023-08-28 07:11 UTC, jessekelly881 commented on packages/platform/src/KeyValueStore.ts
> +  ) => Effect.Effect<never, PlatformError.PlatformError, void>
Makes sense. Presumably, it should still throw if it can't set the key, no?

2023-08-28 08:04 UTC, tim-smart commented on packages/platform/src/KeyValueStore.ts
> +  ) => Effect.Effect<never, PlatformError.PlatformError, void>
Yes in the same way directly calling .set can fail (quota errors, file system errors etc)

2023-08-28 20:07 UTC, jessekelly881 commented
I'm referring to [this code](https://github.com/Effect-TS/platform/blob/850482419230662799d6343965ca1e9249f95b25/packages/platform-node/src/internal/fileSystem.ts#L312) but I might be misunderstanding what this does..

2023-08-28 21:13 UTC, tim-smart commented
> I'm referring to [this code](https://github.com/Effect-TS/platform/blob/850482419230662799d6343965ca1e9249f95b25/packages/platform-node/src/internal/fileSystem.ts#L312) but I might be misunderstanding what this does..

Ah right, that is only used to prevent race conditions when tracking the current cursor/offset.

2023-08-28 21:48 UTC, tim-smart requested changes

2023-08-28 21:48 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +    has: (key) => impl.get(key).pipe(Effect.map(Option.isSome)),
We try to avoid using the pipe method in library code, as the babel plugin hasn't been updated to compile them away yet.

For simple cases like this, using the data-first api is preferable.

2023-08-28 21:48 UTC, tim-smart commented on packages/platform-node/test/KeyValueStore.test.ts
> +    Effect.provideLayer(self, Kv.layerFileSystem(`${__dirname}/fixtures/kv`)),
When using Layer, ideally you compose the layers first, then only have one `provideLayer` call.

So above this:

```ts
const KeyValueLive = Kv.layerFileSystem(`${__dirname}/fixtures/kv`).pipe(
  Layer.use(Fs.layer),
  Layer.use(Path.layer),
)
```

2023-08-28 21:48 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +        yield* _(fs.makeDirectory(directory))
I wonder if we should set `recursive` to `true` here?

2023-08-28 21:48 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +        clear: fs.remove(directory, { recursive: true }).pipe(Effect.flatMap(() => fs.makeDirectory(directory))),
Same as above regarding the pipe method.

```ts
Effect.zipRight(remove, create)
```

2023-08-28 21:48 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +      Effect.gen(function*(_) {
We should refactor this to not use a generator, something like:

```ts
modify: (key, f) =>
  Effect.flatMap(
    impl.get(key),
    (o) => {
      if (Option.isNone(o)) {
        return Effect.succeedNone
      }
      const newValue = f(o.value)
      return Effect.as(
        impl.set(key, newValue),
        Option.some(newValue)
      )
    }
  )
```

2023-08-28 21:48 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +      const keyPath = (key: string) => path.join(directory, key)
There will be a bug here if a key is used that can't be used in a file name (or if someone tries to use "../../passwd" as a key name 😉 ).

Maybe we just base64 encode them.

2023-08-28 21:50 UTC, tim-smart commented on packages/platform-browser/src/internal/keyValueStore.ts
> +            method: "getItem",
Still need to update the error method names :)

2023-08-28 21:55 UTC, tim-smart commented
Couple more tweaks and then I think we can ship this, nice work.

Also don't feel like you need to squash your commits (unless you really want to haha) - we will "squash and merge" when it is ready regardless.

2023-08-28 22:02 UTC, jessekelly881 commented
Thanks 🙏 Awesome! I will fix them in a little bit.

2023-08-28 23:19 UTC, jessekelly881 commented on packages/platform/src/internal/keyValueStore.ts
> +        yield* _(fs.makeDirectory(directory))
Hmm. Probably. Although I can't image having a nested kv store.

2023-08-28 23:52 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +        yield* _(fs.makeDirectory(directory))
It would be for the case you specify `/tmp/foo/bar`, but `/tmp/foo` doesn't exist yet.

2023-08-29 00:06 UTC, jessekelly881 commented on packages/platform/src/internal/keyValueStore.ts
> +        yield* _(fs.makeDirectory(directory))
Yeah, sorry it took me a minute to realize what that was for. jaja. What if we add it as an argument to layerFileSystem?

2023-08-29 00:12 UTC, jessekelly881 commented on packages/platform/src/internal/keyValueStore.ts
> +      const keyPath = (key: string) => path.join(directory, key)
Ooh good point. Also, if they include a / it might cause issues.

2023-08-29 00:48 UTC, jessekelly881 commented
Also, should I include the lock file or do you want me to remove it?

2023-08-29 00:57 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +        yield* _(fs.makeDirectory(directory))
I think recursive by default is fine, and is often the expected behaviour.

2023-08-29 01:01 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +      const keyPath = (key: string) => path.join(directory, key)
Maybe when get the cross platform hashing module implemented. But for now `btoa` is fine :)

2023-08-29 01:19 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +      const keyPath = (key: string) => path.join(directory, btoa(key))
I did some quick research, and `encodeURIComponent` is the preferred approach. Let's switch to that.

2023-08-29 01:20 UTC, jessekelly881 commented on packages/platform/src/internal/keyValueStore.ts
> +      const keyPath = (key: string) => path.join(directory, btoa(key))
Should we replace it repo wide? Or just here?

2023-08-29 01:21 UTC, tim-smart commented on packages/platform/src/internal/keyValueStore.ts
> +      const keyPath = (key: string) => path.join(directory, btoa(key))
This is the only place we need to encode file names, so just here.

2023-08-29 02:23 UTC, tim-smart commented
🚀

2023-08-29 02:23 UTC, merged