feat: added clipboard api
Effect-TS/platform pull request #131
Opened 2023-09-01 03:57 UTC by jessekelly881

2023-09-01 04:38 UTC, tim-smart commented
It would be nice to support attachments/binary too. Maybe a ClipboardItem data structure?

2023-09-01 18:23 UTC, jessekelly881 commented
Agreed. Let me take a look at adding it.

2023-09-01 23:54 UTC, jessekelly881 commented
So, adding this for browser is easy enough but all of the node/deno "copy-to-clipboard" libraries that I've seen only support text(not binary) and rely on piping it to a cli command. I don't know if it's possible to do this with binary data.

2023-09-04 19:56 UTC, jessekelly881 commented
I don't think this is possible in general sense on platform this relies on piping the input the specific cli tools. Unless we find a way around this what do you think should be given priority: supporting node(or bun/deno) or allowing passing binary data to the clipboard?

2023-09-04 21:19 UTC, tim-smart commented
OK, for now you can remove it from the base /platform package and just keep it in platform-browser

2023-09-07 21:41 UTC, tim-smart requested changes

2023-09-07 21:41 UTC, tim-smart commented on docs/platform-browser/Clipboard.ts.md
> +  - [layerLive](#layerlive)
This should be `layer` to be consistent with the other modules.

2023-09-07 21:41 UTC, tim-smart commented on docs/platform-browser/Clipboard.ts.md
> +  read: Effect.Effect<never, PlatformError, ClipboardItems>
Add `readonly` modifiers here to match the other modules.

2023-09-07 21:41 UTC, tim-smart commented on packages/platform-browser/src/internal/clipboard.ts
> +export const tag = Tag<Clipboard.Clipboard>("@effect/platform/Clipboard")
s/platform/platform-browser/

2023-09-07 21:41 UTC, tim-smart commented on packages/platform-browser/src/Clipboard.ts
> +  impl: Omit<Clipboard, "clear">
This needs to be updated to match the internal signature.

2023-09-07 22:41 UTC, tim-smart approved these changes

2023-09-10 22:46 UTC, merged