adding offset tracking and `seek` with semaphore
Effect-TS/platform pull request #46
Opened 2023-08-01 10:34 UTC by fubhy

2023-08-01 10:40 UTC, fubhy commented on packages/platform/src/FileSystem.ts
> +export type SeekMode =
What's the best way to model this for a pleasant API with branded types or sth. (e.g. `SeekMode.End`) without using enums?

2023-08-01 21:39 UTC, tim-smart requested changes
Looks like a good start! I have left some feedback.

2023-08-01 21:39 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +    private position: FileSystem.Size = FileSystem.Size(0)
I think we should just use a plain bigint here.

2023-08-01 21:39 UTC, tim-smart commented on packages/platform/src/FileSystem.ts
> +export type SeekMode = Brand.Branded<0 | 1, "SeekMode">
Lets make SeekMode a simple union of strings. `"start" | "current"`

2023-08-01 21:39 UTC, tim-smart commented on packages/platform/src/FileSystem.ts
> +    whence: SeekMode
I think `from` is a better name.

2023-08-01 21:39 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +      return this.semaphore.withPermits(1)(Effect.suspend(() => loop(buffer)))
Don't need to suspend here.

2023-08-01 21:39 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +      const loop = (buffer: Uint8Array): Effect.Effect<never, Error.PlatformError, void> =>
I think this should be moved to a private function on the class. It doesn't need closure of any other params.

2023-08-01 21:40 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +    private position: FileSystem.Size = FileSystem.Size(0)
Also, is this valid if the file is opened in append mode?

2023-08-01 23:54 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +    private position: FileSystem.Size = FileSystem.Size(0)
I think we should only do offset tracking once seek has been called.

2023-08-02 06:35 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +    private position: FileSystem.Size = FileSystem.Size(0)
I personally really like relative seeking. It comes at practically no additional cost in terms of complexity for the internal api and is really convenient when interacting with the file descriptor. Ultimate it's your call but I'm a big fan ;-)

2023-08-02 06:37 UTC, fubhy commented on packages/platform/src/FileSystem.ts
> +    whence: SeekMode
Agreed. Deno calls it `whence`

2023-08-02 06:43 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +    private position: FileSystem.Size = FileSystem.Size(0)
And yes, this is "valid" when opened in append mode. Append mode (to my knowledge) simply "pretends" that the 0 position is at the current end of the file. Hence, `seek(0)` would just reset it to that position. I can add a test to showcase that.

2023-08-02 06:44 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +    private position: FileSystem.Size = FileSystem.Size(0)
Note that negative offsets beyond the "0" position (whether append mode or not) are always treated as "0"

2023-08-02 06:54 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +    private position: FileSystem.Size = FileSystem.Size(0)
But now that you mentioned it... It might behave weirdly when reading. We could turn that into a feature and only use the cursor for reading in append mode and ignore it (and also not update it) during writes.

That would give you a steady read cursor whilst continuously appending to the file.

2023-08-02 07:18 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +      return this.semaphore.withPermits(1)(Effect.suspend(() => loop(buffer)))
I think this suspend is required for the semaphore to work here, no? Otherwise, the subsequent `nodeWriteAll` call is invoked immediately.

2023-08-02 07:54 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +      return this.semaphore.withPermits(1)(Effect.suspend(() => loop(buffer)))
No because effects are lazy and don't execute immediately.

You need to use suspend when accessing this.position however, as accessing a mutable variable is a side effect.

2023-08-02 07:58 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +      return this.semaphore.withPermits(1)(Effect.suspend(() => loop(buffer)))
I could add a `suspend` there of course but since we are already within a single-permit semaphore at that point I thought it would be more efficient to add the supend only once at the "root"

2023-08-02 08:06 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +      return this.semaphore.withPermits(1)(Effect.suspend(() => loop(buffer)))
This is the line I'm talking about. Here we are accessing `this.position` and that should happen within the semaphore. So we need to have that in an effect somewhere: https://github.com/Effect-TS/platform/blob/f5ffaabd5040b1ff57779d4cbd411f73353d1c1e/packages/platform-node/src/internal/fileSystem.ts#L329

2023-08-02 08:08 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +      return this.semaphore.withPermits(1)(Effect.suspend(() => loop(buffer)))
I think we should move the suspend to where it is actually needed, as the intention is a lot clearer.

2023-08-02 08:22 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +      return this.semaphore.withPermits(1)(Effect.suspend(() => loop(buffer)))
Ok. I moved it into `writeAllChunk` instead.

2023-08-02 08:35 UTC, tim-smart requested changes

2023-08-02 08:35 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +          nodeWriteAll(this.fd, buffer, undefined, undefined, this.append ? undefined : Number(this.position)),
You can move the suspend to this line, instead of wrapping the entire operation.

2023-08-02 08:40 UTC, tim-smart submitted a review, later dismissed

2023-08-02 08:40 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +            nodeWrite(this.fd, buffer, undefined, undefined, this.append ? undefined : Number(this.position)),
You can move the suspend to this line.

2023-08-02 08:40 UTC, tim-smart commented on packages/platform/src/FileSystem.ts
> +export const SeekMode = {
I would just remove this :)

2023-08-02 08:46 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +          nodeWriteAll(this.fd, buffer, undefined, undefined, this.append ? undefined : Number(this.position)),
Ok that makes sense! I moved all the other ones closer to the underlying `this.position` lookup too.

2023-08-02 08:46 UTC, fubhy commented on packages/platform/src/FileSystem.ts
> +export const SeekMode = {
Ok

2023-08-02 08:50 UTC, fubhy commented
Ready for another round of feedback. Are we happy with the way it's handling relative seek mode and `append`?

2023-08-02 08:59 UTC, fubhy commented on packages/platform-node/test/FileSystem.test.ts
> +    })))
This demonstrates the "read cursor" in append mode.

2023-08-02 09:16 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +            this.position = length ?? 0n
Do you need to check if the position is larger than length before doing this?

2023-08-02 09:21 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +            this.position = length ?? 0n
Good question. What would you expect the behvior of `truncate` to be with the cursor?

2023-08-02 09:27 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +            this.position = length ?? 0n
Updated that bit... I think this is what's expected:

If `length` is larger than current `position`, keep the current `position`
Otherwise, set it to `length` (or `0` if `length` is undefined)

2023-08-02 09:29 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +            this.position = length ?? 0n
I think if you truncate below the current cursor, then the cursor gets moved back (which is the behaviour here)

But if the cursor remains under the new length, then it is preserved.

2023-08-02 09:48 UTC, tim-smart commented on packages/platform-node/src/internal/fileSystem.ts
> +            this.position = length ?? 0n
I don't think you have pushed your change yet.

2023-08-02 09:53 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +            this.position = length ?? 0n
Umh, I have but github hasn't updated the PR: https://github.com/fubhy/platform/commit/b7356898b31443733cc924ca6bd5d6faa6cb0a42

2023-08-02 09:54 UTC, fubhy commented on packages/platform-node/src/internal/fileSystem.ts
> +            this.position = length ?? 0n
Pushed another commit... Interesting, I've not seen that before on github ;-)

2023-08-02 23:55 UTC, merged