add base64, base64url and hex encoding
Effect-TS/platform pull request #96
Opened 2023-08-23 13:27 UTC by fubhy

Moving this to effect/platform per your suggestion @tim-smart.

Original issue: https://github.com/Effect-TS/data/issues/469

---

I think moving this to `effect/platform` makes sense if we want to use native apis where possible. However I ran into a couple issues while doing so ... The `Buffer` APIs for base64 & hex encoding are anything but strict. Instead of throwing an error in case of invalid input, they simply ignore any invalid characters and whitespace and produce garbage. I'm wondering if we should even rely on Buffer for that reason? I'd personally rather use the custom implementation with strict encoding & decoding. Another option would be to run a regex for input validation. That'd negatively impact performance though.

2023-08-23 17:09 UTC, fubhy commented
For consideration:

```
 BENCH  Summary

  platform - test/Encoding.bench.ts > Base64 > Encode
    1.92x faster than platform-node

  platform-node - test/Encoding.bench.ts > Base64 > Decode
    1.03x faster than platform
```

TL;DR: Enoding is consistently significantly faster with the custom algorithm. Decoding is marginally faster through the `Buffer` API.

2023-08-23 22:28 UTC, tim-smart requested changes
OK after considering the lack of performance impact, having separate implementations for each platform doesn't make much sense.

So continuing this in /data is likely the better option.

2023-08-23 22:28 UTC, tim-smart commented on packages/platform/src/internal/encoding/Base64.ts
> +    throw new TypeError("Invalid base64 string")
I think the internal apis should just return Either instead of throwing.

2023-08-23 22:28 UTC, tim-smart commented on packages/platform-node/src/Encoding.ts
> +export const encodeBase64 = Base64.encode
The public modules should all be annotated with types.

2023-08-24 06:40 UTC, fubhy commented
Ok! Continuing in /data

2023-08-24 06:40 UTC, closed without merging